### ISSUE TITLE
First frame True Global Reset Mode

### ISSUE THREAD

**Issue by tgreffe** [hpearnshaw/cmost-analysis#4]
In both Pseudo and True GlobalReset modes, the first frame is not meaningless (as opposite to Rolling Reset)
So it must be kept when opening the fits.

**Comment by hpearnshaw** [comment]
Exposure() will now ignore the first frame only in the DEFAULT and ROLLINGRESET readout modes, and in all other cases will include the first frame. Is it safe to assume that any future modes will generally not need to ignore the first frame?
